# Generated by Django 4.2.2 on 2023-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer_qq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, max_length=100)),
                ('steam_ID', models.CharField(max_length=17)),
                ('last_two_weeks', models.FloatField(blank=True, max_length=500)),
                ('ATH', models.FloatField(blank=True, max_length=10000)),
                ('score_sum', models.FloatField(blank=True, max_length=2)),
                ('status_U_count', models.FloatField(blank=True, max_length=2)),
                ('level', models.IntegerField(blank=True, max_length=1000)),
                ('badges', models.IntegerField(blank=True, max_length=1000)),
                ('games', models.IntegerField(blank=True, max_length=10000)),
                ('friends', models.IntegerField(blank=True, max_length=10000)),
                ('groups', models.IntegerField(blank=True, max_length=1000)),
                ('screenshots', models.IntegerField(blank=True, max_length=10000)),
                ('Reviews', models.IntegerField(blank=True, max_length=10000)),
                ('Cluster', models.IntegerField(blank=True, max_length=5)),
                ('R', models.FloatField(blank=True, max_length=10)),
            ],
        ),
    ]
